apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app: spring-boot-k8s
